---
- name: Put a config file in place
  copy:
    dest: /tmp/awslogs.conf
    group: root
    mode: 0600
    owner: root
    src: awslogs.conf

- name: Download the agent dependencies
  get_url:
    dest: /tmp/AgentDependencies.tar.gz
    group: root
    owner: root
    mode: 0660
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/AgentDependencies.tar.gz

- name: Untar agent dependencies
  shell: tar xvf AgentDependencies.tar.gz -C /tmp/

- name: Download the installer
  get_url:
    dest: /tmp/awslogs-agent-setup.py
    group: root
    owner: root
    mode: 0600
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py

- name: Install the CloudWatch Logs agent
  shell: python /tmp/awslogs-agent-setup.py -n -r {{ aws_regions }} -c /tmp/awslogs.conf --dependency-path /tmp/AgentDependencies

- name: Enable awslogs service
  service:
    name: awslogs
    enabled: yes
    state: started
